version: "3"

env:
  MIGRATE_VERSION: "v4.18.2"

tasks:
  setup:
    desc: Install development tools
    dotenv:
      - .env
    cmds:
      - echo "Installing development tools..."
      - go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@{{.MIGRATE_VERSION}}
      - go install github.com/air-verse/air@latest

  dev:
    desc: Start the application with Air
    dotenv:
      - .env
    cmds:
      - air

  migrate-up:
    desc: Run all pending local migrations
    dotenv:
      - .env
    cmds:
      - migrate -path ./db/migrations -database "postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=$DB_SSL_MODE" up

  migrate-down:
    desc: Rollback the last local migration
    dotenv:
      - .env
    cmds:
      - migrate -path ./db/migrations -database "postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=$DB_SSL_MODE" down 1

  migrate-up-neon:
    desc: Run all pending migrations against Neon
    dotenv:
      - .env.neon
    cmds:
      - migrate -path ./db/migrations -database "postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=$DB_SSL_MODE" up

  migrate-down-neon:
    desc: Rollback the last migration on Neon
    dotenv:
      - .env.neon
    cmds:
      - migrate -path ./db/migrations -database "postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=$DB_SSL_MODE" down 1

  migrate-create:
    desc: "Create a new migration file (usage: task migrate-create NAME=create_orders_table)"
    cmds:
      - migrate create -seq -ext sql -dir ./db/migrations {{.NAME}}

  migrate-force:
    desc: "Force local migration version (usage: task migrate-force VERSION=1)"
    dotenv:
      - .env
    cmds:
      - migrate -path ./db/migrations -database "postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=$DB_SSL_MODE" force {{.VERSION}}

  migrate-force-neon:
    desc: "Force Neon migration version (usage: task migrate-force-neon VERSION=1)"
    dotenv:
      - .env.neon
    cmds:
      - migrate -path ./db/migrations -database "postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=$DB_SSL_MODE" force {{.VERSION}}

  service-create:
    desc: "Creates a new service folder with the standard Go files and package declarations."
    cmds:
      - mkdir -p ./internal/services/{{.NAME}}
      - printf 'package {{.NAME}}\n' > ./internal/services/{{.NAME}}/model.go
      - printf 'package {{.NAME}}\n' > ./internal/services/{{.NAME}}/repository.go
      - printf 'package {{.NAME}}\n' > ./internal/services/{{.NAME}}/service.go
      - printf 'package {{.NAME}}\n' > ./internal/services/{{.NAME}}/handler.go
      - printf 'package {{.NAME}}\n' > ./internal/services/{{.NAME}}/errors.go

  docker-up:
    desc: Start Docker Compose services
    cmds:
      - docker compose up -d

  docker-down:
    desc: Stop Docker Compose services and remove volumes
    cmds:
      - docker compose down -v
